# -*- coding: utf-8 -*-
"""Stock real time web scrape

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VS4rJoJQIL9-uPL14DnoFwDUh7uLWAca
"""

import requests
from bs4 import BeautifulSoup

url = 'https://www.moneycontrol.com/india/stockpricequote/telecommunications-service/vodafoneidealimited/IC8'

response = requests.get(url)

soup = BeautifulSoup(response.text,'html.parser')

print(soup.prettify())

price = soup.find_all('div',{'class':"pcnsb div_live_price_wrap"})[0].find('span').text
print(price)

def priceTracker():
  url = 'https://www.moneycontrol.com/india/stockpricequote/telecommunications-service/vodafoneidealimited/IC8'
  response = requests.get(url)
  soup = BeautifulSoup(response.text,'html.parser')
  price = soup.find_all('div',{'class':"pcnsb div_live_price_wrap"})[0].find('span').text
  print(price)